### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by xilinniao123** [mswellhao/chineseNER#4]
hi :
thanks for sharing this project. i follow your instruction and train the model,all the parameters are defualt. after 10 epoch iteration,i got the final model "model_9"。  with this model,i do some extract,but result is so bad,for example 
$more rawdata
李彦宏是腾讯公司的好老板。
$more result
[[[0, 1, "PER"]]]
the person name “李彦宏” 都没有识别出来
can you give me some suggestion?

**Comment by mswellhao** [comment]
maybe you need more training data

**Comment by xilinniao123** [comment]
thanks for your reply,is there any paper related to this project?
